name: "Jenkins"
description: "Start a jenkins instance"
inputs:
  version:
    description: "The jenkins version to use (default: lts)"
    required: false
    default: "lts"

  dump-version-path:
    description: "path to dump version files (see src/init.groovy.d/version.groovy)"
    required: false

  # override
  plugins:
    description: "plugins to install (format plugin[:version])"
    required: false
  init_groovy:
    description: "folder with groovy script to run in init.groovy.d"
    required: false
  entrypoint:
    description: "entrypoint folder (must contain init.sh with default functions, see src/entrypoint/init.sh)"
    required: false


  # master configuration (see init.groovy.d/10-config-master.groovy)
  master-num-executors:
    required: false
    default: 4
  master-labels:
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: "Prepare files"
      shell: "bash"
      env:
        INPUT_PLUGINS: ${{ inputs.plugins }}
        INPUT_INIT_GROOVY: ${{ inputs.init_groovy }}
        INPUT_ENTRYPOINT: ${{ inputs.entrypoint }}
        INPUT_MASTER_NUM_EXECUTORS: ${{ inputs.master-num-executors }}
        INPUT_MASTER_LABELS: ${{ inputs.master-labels }}
        INPUT_DUMP_VERSION_PATH: ${{ inputs.dump-version-path }}
      run: |
        chmod +x ${{ github.action_path }}/prepare.sh
        ${{ github.action_path }}/prepare.sh ${{inputs.version}}

    - name: "run jenkins-${{inputs.version}}"
      uses: ./.jenkins

branding:
  icon: 'server'
  color: red
