name: "Jenkins"
description: "Start a jenkins instance"
inputs:
  version:
    description: "The jenkins version to use (default: lts)"
    required: false
    default: "lts"
runs:
  using: "composite"
  steps:
    - name: "Prepare files for build"
      shell: "bash"
      run: |
        chmod +x ./prepare_build.sh
        ./prepare_build.sh ${{inputs.version}} ./.jenkins-build

    - name: "run jenkins-${{inputs.version}}"
      uses: ./.jenkins-build

    - name: "cleanup"
      shell: "bash"
      run: |
        rm -rf ./.jenkins-build

branding:
  icon: 'server'
  color: red
