on:
  schedule:
    # once a week to check with latest version of plugins
    - cron:  '0 19 * * 1'

jobs:
  jenkins-lts:
    runs-on: ubuntu-latest
    name: test on jenkins-lts
    steps:
      - uses: actions/checkout@v2
        with:
           ref: lts
      - name: test jenkins-lts
        uses: ./jenkins-lts/
