on:
  schedule:
    # once a week to check with latest version of plugins
    - cron:  '0 19 * * 1'
  workflow_dispatch:

jobs:
  jenkins-lts:
    runs-on: ubuntu-latest
    name: test on jenkins-lts
    env:
      ACTION_JENKINS_VERSION: ${{github.workspace}}/jenkins-lts/.version
    steps:
      - uses: actions/checkout@v3
      - name: test jenkins-lts
        uses: ./jenkins-lts/
      - name: Update last good version
        if: github.event_name != 'pull_request'
        run: |
          chmod +x ./update-version.sh
          ./update-version.sh jenkins-lts lts jenkins-last

          git status --porcelain ./jenkins-last README.md
          if [ $(git status --porcelain ./jenkins-last README.md | wc -l) -eq 0 ]; then
              echo "jenkins_last_changed=false" >> ${GITHUB_ENV}
          else
              echo "jenkins_last_changed=true" >> ${GITHUB_ENV}
              git diff
          fi
      - name: push last good version
        if: github.event_name != 'pull_request' && env.jenkins_last_changed == 'true'
        run: |
          git config --global user.name 'jenkins-action'
          git config --global user.email 'jenkins-action@users.noreply.github.com'
          git add ./jenkins-last README.md
          git commit -m "[bot] Update last good jenkins version"
          git push
