on:
  schedule:
    # once a week to check with latest version of plugins
    - cron:  '0 19 * * 1'
  workflow_dispatch:

jobs:
  jenkins-lts:
    runs-on: ubuntu-latest
    name: test on jenkins-lts
    env:
      ACTION_JENKINS_VERSION: ${{github.workspace}}/jenkins-lts/.version
    steps:
      - uses: actions/checkout@v3

      - name: test jenkins-lts
        uses: ./jenkins-lts/

      - name: Update last good version
        if: github.event_name != 'pull_request'
        run: |
          chmod +x ./update-version.sh
          ./update-version.sh jenkins-lts lts jenkins-last

      - name: auto commit jenkins-last
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "[bot] Update last good version"
          file_pattern: jenkins-last README.md
