name: bump last-good-version

on:
  schedule:
    # once a week to check with latest version of plugins
    - cron:  '0 19 * * 1'
  workflow_dispatch:

jobs:
  jenkins-lts:
    runs-on: ubuntu-latest
    name: test on jenkins-lts
    steps:
      - uses: actions/checkout@v3

      - name: test jenkins-lts
        uses: ./
        env:
          ACTION_JENKINS_VERSION: ${{github.workspace}}/last-good-version

      - name: double check jenkins last good version
        uses: ./
        with:
          version: last-good-version

      - name: update README.md
        run: |
          chmod +x update_version.sh
          ./update_version.sh last-good-version

      - name: auto commit last-good-version
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "[bot] Update last good version"
          file_pattern: last-good-version README.md
